import localFont from "next/font/local";

import "./globals.css";

const font = localFont({
  src: [
    {
      path: "../public/font/YekanBakhMedium.woff",
      style: "normal",
    }
  ]
})



export const metadata = {
  title: "rvanafzar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={font.className}>{children}</body>
    </html>
  );
}
